import type {
  Investigation,
  TargetProfile,
  Evidence,
  SearchRecord,
  FavoriteItem,
  Note,
  Finding,
  NotificationItem,
  AppSettings,
  ActivityLog
} from '../types';

export const INITIAL_SETTINGS: AppSettings = {
  theme: 'dark',
  language: 'English',
  autoSave: true,
  notifications: true,
  dateFormat: 'YYYY-MM-DD',
  defaultReportFormat: 'PDF',
  includeEvidence: true,
  includeScreenshots: true,
  includeNotes: true,
  analystName: 'Lakshmiprasad',
  analystRole: 'Cyber Security Intern',
  analystOrg: 'Enterprise SOC & OSINT Lab',
};

export const INITIAL_INVESTIGATIONS: Investigation[] = [
  {
    id: 'INV-2026-001',
    name: 'Corporate Exposure Assessment',
    analystName: 'Lakshmiprasad',
    date: '2026-07-28',
    priority: 'High',
    status: 'In Progress',
    description: 'Comprehensive OSINT audit of public cloud endpoints, subdomains, and corporate identity leaks for Apex Technologies Group.',
    notes: 'Discovered several unlinked subdomains and public document metadata containing analyst signatures.',
    tags: ['OSINT', 'CloudExposure', 'DEMO DATA'],
    targetIds: ['TRG-2026-001'],
    evidenceIds: ['EVD-2026-001', 'EVD-2026-002'],
    createdAt: '2026-07-28T09:15:00Z',
    updatedAt: '2026-07-30T10:30:00Z',
  },
  {
    id: 'INV-2026-002',
    name: 'Public Web Presence Review',
    analystName: 'Lakshmiprasad',
    date: '2026-07-25',
    priority: 'Medium',
    status: 'Completed',
    description: 'Reviewing social footprint and public domain infrastructure for CyberDefense Solutions Ltd.',
    notes: 'All core domains enforce HTTPS and modern security headers. DNSSEC enabled.',
    tags: ['WebPresence', 'DNS', 'DEMO DATA'],
    targetIds: ['TRG-2026-002'],
    evidenceIds: ['EVD-2026-003'],
    createdAt: '2026-07-25T14:20:00Z',
    updatedAt: '2026-07-27T16:45:00Z',
  },
  {
    id: 'INV-2026-003',
    name: 'Security Awareness Investigation',
    analystName: 'Lakshmiprasad',
    date: '2026-07-20',
    priority: 'Low',
    status: 'New',
    description: 'Defensive investigation into publicly indexable email lists for employee phishing defense training.',
    notes: 'Initial search queries generated for Google Dorks and public GitHub code mentions.',
    tags: ['PhishingDefense', 'Training', 'DEMO DATA'],
    targetIds: ['TRG-2026-001', 'TRG-2026-003'],
    evidenceIds: [],
    createdAt: '2026-07-20T11:00:00Z',
    updatedAt: '2026-07-20T11:00:00Z',
  },
];

export const INITIAL_TARGETS: TargetProfile[] = [
  {
    id: 'TRG-2026-001',
    fullName: 'Apex Tech Corp HQ',
    username: 'apex_sec_ops',
    company: 'Apex Technologies Group',
    organization: 'Enterprise Solutions Inc',
    jobTitle: 'Corporate Infrastructure Target',
    email: 'security@apextech.example.com',
    phone: '+1-800-555-0199',
    website: 'https://apextech.example.com',
    domain: 'apextech.example.com',
    ipAddress: '104.21.55.12',
    country: 'United States',
    city: 'San Francisco',
    address: '100 Cyber Tech Way, Suite 400',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/apex-tech',
      github: 'https://github.com/apex-technologies',
      twitter: 'https://x.com/apextech_sec',
    },
    notes: 'Primary corporate infrastructure domain. Used for main web services.',
    tags: ['Corporate', 'Target', 'DEMO DATA'],
    isFavorite: true,
    createdAt: '2026-07-28T09:30:00Z',
    updatedAt: '2026-07-30T08:15:00Z',
  },
  {
    id: 'TRG-2026-002',
    fullName: 'CyberDefense Solutions',
    username: 'cyberdef_global',
    company: 'CyberDefense Global',
    organization: 'Defense Systems Ltd',
    jobTitle: 'Managed Security Target',
    email: 'contact@cyberdefense.example.org',
    phone: '+44-20-7946-0912',
    website: 'https://cyberdefense.example.org',
    domain: 'cyberdefense.example.org',
    ipAddress: '185.199.108.153',
    country: 'United Kingdom',
    city: 'London',
    address: '25 Security Plaza, EC2A 1NT',
    socialLinks: {
      linkedin: 'https://linkedin.com/company/cyberdefense',
      github: 'https://github.com/cyberdefense-org',
    },
    notes: 'Secondary target domain for defense intelligence testing.',
    tags: ['MSSP', 'Defense', 'DEMO DATA'],
    isFavorite: false,
    createdAt: '2026-07-25T14:30:00Z',
    updatedAt: '2026-07-25T14:30:00Z',
  },
  {
    id: 'TRG-2026-003',
    fullName: 'Demo Executive Target',
    username: 'john_apex_exec',
    company: 'Apex Technologies Group',
    organization: 'Executive Leadership',
    jobTitle: 'Chief Information Officer',
    email: 'j.doe@apextech.example.com',
    phone: '+1-800-555-0144',
    website: 'https://apextech.example.com/leadership',
    domain: 'apextech.example.com',
    ipAddress: '104.21.55.12',
    country: 'United States',
    city: 'New York',
    address: '500 Fifth Avenue',
    socialLinks: {
      linkedin: 'https://linkedin.com/in/johndoe-apex',
    },
    notes: 'Executive profile for public awareness assessment.',
    tags: ['Executive', 'Person', 'DEMO DATA'],
    isFavorite: true,
    createdAt: '2026-07-20T11:30:00Z',
    updatedAt: '2026-07-20T11:30:00Z',
  },
];

export const INITIAL_EVIDENCE: Evidence[] = [
  {
    id: 'EVD-2026-001',
    investigationId: 'INV-2026-001',
    fileName: 'dns_subdomain_enum_screenshot.png',
    fileSize: 452100,
    fileType: 'image/png',
    uploadDate: '2026-07-28T10:14:00Z',
    description: 'Screenshot of DNS public subdomain discovery record list showing dev.apextech.example.com',
    tags: ['DNS', 'Subdomains', 'Screenshot', 'DEMO DATA'],
  },
  {
    id: 'EVD-2026-002',
    investigationId: 'INV-2026-001',
    fileName: 'whois_apextech_domain_record.pdf',
    fileSize: 1240000,
    fileType: 'application/pdf',
    uploadDate: '2026-07-29T08:45:00Z',
    description: 'Official WHOIS export document for apextech.example.com',
    tags: ['WHOIS', 'PDF', 'Registrar', 'DEMO DATA'],
  },
  {
    id: 'EVD-2026-003',
    investigationId: 'INV-2026-002',
    fileName: 'ssl_certificate_transparency_log.txt',
    fileSize: 34500,
    fileType: 'text/plain',
    uploadDate: '2026-07-26T15:20:00Z',
    description: 'Public Certificate Transparency (CT) log history entries.',
    tags: ['SSL', 'Certificate', 'Logs', 'DEMO DATA'],
  },
];

export const INITIAL_SEARCH_HISTORY: SearchRecord[] = [
  {
    id: 'SRC-2026-001',
    query: 'apextech.example.com',
    module: 'WHOIS Lookup',
    type: 'Domain',
    timestamp: '2026-07-30T09:12:00Z',
    status: 'Completed',
    resultCount: 4,
    searchUrl: 'https://lookup.icann.org/en/lookup?q=apextech.example.com',
  },
  {
    id: 'SRC-2026-002',
    query: '104.21.55.12',
    module: 'IP Information',
    type: 'IP',
    timestamp: '2026-07-30T08:45:00Z',
    status: 'Completed',
    resultCount: 4,
    searchUrl: 'https://ipinfo.io/104.21.55.12',
  },
  {
    id: 'SRC-2026-003',
    query: 'security@apextech.example.com',
    module: 'Email Intelligence',
    type: 'Email',
    timestamp: '2026-07-29T16:30:00Z',
    status: 'Completed',
    resultCount: 4,
    searchUrl: 'https://www.google.com/search?q=%22security@apextech.example.com%22',
  },
  {
    id: 'SRC-2026-004',
    query: 'site:apextech.example.com filetype:pdf',
    module: 'Advanced Query Builder',
    type: 'Domain',
    timestamp: '2026-07-28T11:20:00Z',
    status: 'Completed',
    resultCount: 1,
    searchUrl: 'https://www.google.com/search?q=site%3Aapextech.example.com+filetype%3Apdf',
  },
];

export const INITIAL_FAVORITES: FavoriteItem[] = [
  {
    id: 'FAV-001',
    category: 'tool',
    targetId: 'whois',
    title: 'WHOIS Lookup',
    subtitle: 'Domain registration & registrar info',
    iconName: 'Globe',
    createdAt: '2026-07-25T10:00:00Z',
  },
  {
    id: 'FAV-002',
    category: 'tool',
    targetId: 'dorks',
    title: 'Advanced Query Builder',
    subtitle: 'Google Dorks and public search generator',
    iconName: 'Search',
    createdAt: '2026-07-25T10:05:00Z',
  },
  {
    id: 'FAV-003',
    category: 'investigation',
    targetId: 'INV-2026-001',
    title: 'Corporate Exposure Assessment',
    subtitle: 'High Priority OSINT Audit',
    iconName: 'FolderLock',
    createdAt: '2026-07-28T10:00:00Z',
  },
  {
    id: 'FAV-004',
    category: 'target',
    targetId: 'TRG-2026-001',
    title: 'Apex Tech Corp HQ',
    subtitle: 'apextech.example.com',
    iconName: 'UserCheck',
    createdAt: '2026-07-28T10:30:00Z',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 'NTE-2026-001',
    title: 'Subdomain Recon Notes',
    content: '## Findings\n- `dev.apextech.example.com` resolves to staging CDN.\n- Public SSL certificate issued by Let\'s Encrypt.\n- No credential exposure found.\n\n### Action Items\n1. Verify CSP headers on secondary web server.\n2. Ensure SPF/DMARC DNS records are enforcing `p=reject`.',
    entityType: 'investigation',
    entityId: 'INV-2026-001',
    tags: ['Subdomains', 'Notes', 'DEMO DATA'],
    createdAt: '2026-07-28T11:45:00Z',
    updatedAt: '2026-07-29T14:10:00Z',
  },
  {
    id: 'NTE-2026-002',
    title: 'General OSINT Methodologies',
    content: 'Defensive OSINT checklist:\n- [x] Verify domain WHOIS Privacy status\n- [x] Check MX and TXT SPF records\n- [ ] Audit publicly available employee email structures\n- [x] Document image EXIF data',
    entityType: 'general',
    tags: ['Checklist', 'Methodology', 'DEMO DATA'],
    createdAt: '2026-07-26T09:00:00Z',
    updatedAt: '2026-07-26T09:00:00Z',
  },
];

export const INITIAL_FINDINGS: Finding[] = [
  {
    id: 'FND-2026-001',
    investigationId: 'INV-2026-001',
    title: 'Unrestricted Metadata in Public PDFs',
    severity: 'Medium',
    description: 'Publicly downloadable corporate whitepapers on `apextech.example.com` contained creator software versions and interior workstation path names in PDF EXIF headers.',
    source: 'Document Metadata Extractor Tool',
    createdAt: '2026-07-28T12:00:00Z',
  },
  {
    id: 'FND-2026-002',
    investigationId: 'INV-2026-001',
    title: 'Missing DMARC Enforcement',
    severity: 'High',
    description: 'DMARC TXT record configured with `p=none`. Mail servers do not instruct recipients to quarantine or reject spoofed corporate messages.',
    source: 'DNS Lookup Module',
    createdAt: '2026-07-29T09:30:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NTF-001',
    title: 'Welcome to Unified Recon Dashboard',
    message: 'System operational. LocalStorage and IndexedDB engines ready.',
    type: 'info',
    read: false,
    timestamp: '2026-07-30T08:00:00Z',
  },
  {
    id: 'NTF-002',
    title: 'Investigation Initialized',
    message: 'Corporate Exposure Assessment (INV-2026-001) updated.',
    type: 'success',
    read: true,
    timestamp: '2026-07-29T10:30:00Z',
  },
];

export const INITIAL_ACTIVITY: ActivityLog[] = [
  {
    id: 'ACT-001',
    action: 'Investigation Created',
    details: 'Analyst Lakshmiprasad created INV-2026-001: Corporate Exposure Assessment',
    timestamp: '2026-07-28T09:15:00Z',
    category: 'Investigation',
  },
  {
    id: 'ACT-002',
    action: 'Target Profile Added',
    details: 'Added target TRG-2026-001 (Apex Tech Corp HQ)',
    timestamp: '2026-07-28T09:30:00Z',
    category: 'Target',
  },
  {
    id: 'ACT-003',
    action: 'Evidence Uploaded',
    details: 'Uploaded dns_subdomain_enum_screenshot.png (452 KB)',
    timestamp: '2026-07-28T10:14:00Z',
    category: 'Evidence',
  },
  {
    id: 'ACT-004',
    action: 'OSINT Search Executed',
    details: 'Executed WHOIS lookup for apextech.example.com',
    timestamp: '2026-07-30T09:12:00Z',
    category: 'Search',
  },
];
